! file WakeTrajLinearGaussianField.f90
! Calculate through linear response theory the plasma_wave field generated by a Gaussian beam
! called by InitialStep, TimeEvolution  
! see documentaion in WakeTrajDoc
! description of main variables is given in WakeTrajModule.90
! author Gilles Maynard CNRS/LPGP/ITFIP
! version 16/03/2017
!> subroutine calculation the linear plasma field generated by a Gaussian laser at time 3
subroutine LinearGaussianField()
  use MdConstant
  use MdLaser
  use MdNumeric
  use MdPlasma
  implicit none
!
  integer, save :: IFlag = 0
  integer :: ir,iz
  real*8 ::  locdL, locX, loceta, locpsi0, locKp, locRad, locRad2, locdistz, locEz, locErad        !< see Equ. (1.15) of the documentation
!*
! Some initialization
  LaserGam3 = sqrt(CriticalDensity_cm3 / (DensPlasma* Dens0Plasma_cm3))
  if(LaserGam3 < 1.d3) then
    LaserRelatBeta3 = sqrt(1.d0 - 1.d0 / LaserGam3**2)
  else
    LaserRelatBeta3 = 1.d0 - (0.5d0 / LaserGam3**2) * (1.d0-0.25d0 / LaserGam3**2)
  endif
  if (Iflag == 0) then
    LaserGam1 = LaserGam3
    LaserGridPosition3 = LaserGridPositionInit
    Iflag = 1
  else
    LaserGridPosition3 = LaserGridPosition1 + (1.d0-0.5d0*(LaserRelatBeta3 + LaserRelatBeta1)) * &
                        & DeltaT
  endif

! plasma quantities depends on the reduced density
  
  locKp = sqrt(DensPlasma)
  locX = 0.5d0 * locKp * LaserDuration
  loceta = sqrt(2.d0 * Pi) * locX * exp(-0.5d0 * locX**2)
  AmpLaser = LaserAmax  / sqrt(1.d0 + time_Rayleigh**2)
  locPsi0 = 0.25d0 * locEta * AmpLaser **2
! longitudinal field is on the radial grid but halfway axial  
  do ir = 0 , IDIMR
    locRad = T1GridRadi(ir) / LaserWaist
    locRad2 = locRad**2
    locEz = locPsi0 * exp(-2.0d0 * locRad2)     
    do iz = 0 , IDIMZ   
      locdistz =T1Gridzi(iz) + dZs2 - LaserGridPosition3
      if(locdistz > 0.d0) then
        T2PlasmaElecZ3(iz,ir) = locEz * cos(locdistz)
      else
        T2PlasmaElecZ3(iz,ir) = 0.d0
      endif
    enddo
  enddo
! Ez is symetric in R
  T2PlasmaElecZ3(:,-1) = T2PlasmaElecZ3(:,0)
! radial field is on the axial grid and halfway of the radial one
  do ir = 0 , IDIMR
    locRad = (T1GridRadi(ir)+dRs2) / LaserWaist
    locRad2 = locRad**2
    locERad = locPsi0 * exp(-2.0d0 * locRad2) * 4.d0 * locRad / LaserWaist     
    do iz = 0 , IDIMZ   
      locdistz =T1Gridzi(iz)  - LaserGridPosition3
      if  (locdistz > 0.d0) then
        T2PlasmaElecRad3(iz,ir) = locERad * sin(locdistz)
      else
        T2PlasmaElecRad3(iz,ir) = 0.d0
      endif
    enddo
  enddo
! Er is anti-symetric in R 
  T2PlasmaElecRad3(:,-1) = -T2PlasmaElecRad3(:,0)
end subroutine LinearGaussianField  